/* prchum.h — C interface to the Prchum core. Generated by cbindgen; do not edit. */

#pragma once

/* Generated with cbindgen:0.29.4 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Event kind: reply to `pc_app_ping`.
 */
#define PC_EVENT_PONG 1

/**
 * Root handle for a core instance. Create with [`pc_app_new`], release with
 * [`pc_app_free`].
 */
typedef struct PcApp PcApp;

/**
 * A review session over one diff source. Create with
 * [`pc_session_new_from_patch`], release with [`pc_session_free`].
 */
typedef struct PcSession PcSession;

/**
 * An event delivered from the core to the shell.
 *
 * The struct and every string it points to are only valid for the duration
 * of the callback invocation; copy anything you need out of it. Strings not
 * applicable to the event kind are null. Shells must tolerate unknown
 * kinds — new kinds are forward compatibility, not an error.
 */
typedef struct PcEvent {
  /**
   * One of the `PC_EVENT_*` constants.
   */
  uint32_t kind;
  /**
   * Sequence number (pong events).
   */
  uint64_t seq;
  /**
   * JSON payload, when the kind carries one.
   */
  const char *payload;
} PcEvent;

/**
 * Shell-provided event sink. Invoked on the core's single dispatch thread;
 * implementations must hop to their UI thread themselves.
 */
typedef void (*PcEventCallback)(const struct PcEvent *event, void *userdata);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the core version as a static nul-terminated UTF-8 string.
 * The returned pointer is owned by the core; do not free it.
 */
const char *pc_version(void);

/**
 * Creates a core instance whose events are delivered to `callback` with
 * `userdata`, one at a time, on a single core-owned thread.
 */
struct PcApp *pc_app_new(PcEventCallback callback, void *userdata);

/**
 * Releases an app handle. Joins the dispatch thread: after this returns,
 * the callback is guaranteed not to run again.
 */
void pc_app_free(struct PcApp *app);

/**
 * Asks the core to answer with a `PC_EVENT_PONG` carrying `seq`, from a
 * worker thread — the smallest possible proof of the async round trip.
 */
void pc_app_ping(struct PcApp *app, uint64_t seq);

/**
 * Opens a review session over a literal unified-diff text.
 *
 * Returns null on failure; when `error_out` is non-null it receives a
 * human-readable message to release with [`pc_string_free`].
 */
struct PcSession *pc_session_new_from_patch(const char *title,
                                            uintptr_t title_len,
                                            const char *patch,
                                            uintptr_t patch_len,
                                            char **error_out);

/**
 * Releases a session handle.
 */
void pc_session_free(struct PcSession *session);

/**
 * The session title. Release with [`pc_string_free`].
 */
char *pc_session_title(const struct PcSession *session);

/**
 * Number of changed files in the session.
 */
uintptr_t pc_session_file_count(const struct PcSession *session);

/**
 * One changed file, hunks and lines included, as JSON:
 * `{old_path, new_path, status, is_binary, hunks: [{header, lines: [{kind,
 * text, raw?, old_line?, new_line?, patch_position?}]}]}`.
 * Returns null for an out-of-range index. Release with [`pc_string_free`].
 */
char *pc_session_file_json(const struct PcSession *session, uintptr_t index);

/**
 * Releases a string returned by this API.
 */
void pc_string_free(char *text);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
