/* prchum.h — C interface to the Prchum core. Generated by cbindgen; do not edit. */

#pragma once

/* Generated with cbindgen:0.29.4 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Event kind: reply to `pc_app_ping`.
 */
#define PC_EVENT_PONG 1

/**
 * Git comparison kinds for [`pc_session_new_from_git`].
 */
#define PC_GIT_WORKTREE 0

/**
 * Index vs HEAD.
 */
#define PC_GIT_STAGED 1

/**
 * `arg1...HEAD` (merge base).
 */
#define PC_GIT_BASE 2

/**
 * Explicit range `arg1..arg2`.
 */
#define PC_GIT_RANGE 3

/**
 * Side values crossing the boundary.
 */
#define PC_SIDE_LEFT 0

#define PC_SIDE_RIGHT 1

/**
 * Review events crossing the boundary.
 */
#define PC_EVENT_REVIEW_COMMENT 0

#define PC_EVENT_REVIEW_APPROVE 1

#define PC_EVENT_REVIEW_REQUEST_CHANGES 2

/**
 * Root handle for a core instance. Create with [`pc_app_new`], release with
 * [`pc_app_free`].
 */
typedef struct PcApp PcApp;

/**
 * The user configuration. Create with [`pc_config_new`], release with
 * [`pc_config_free`].
 */
typedef struct PcConfig PcConfig;

/**
 * A review session over one diff source. Create with one of the
 * `pc_session_new_*` constructors, release with [`pc_session_free`].
 */
typedef struct PcSession PcSession;

/**
 * An event delivered from the core to the shell.
 *
 * The struct and every string it points to are only valid for the duration
 * of the callback invocation; copy anything you need out of it. Strings not
 * applicable to the event kind are null. Shells must tolerate unknown
 * kinds — new kinds are forward compatibility, not an error.
 */
typedef struct PcEvent {
  /**
   * One of the `PC_EVENT_*` constants.
   */
  uint32_t kind;
  /**
   * Sequence number (pong events).
   */
  uint64_t seq;
  /**
   * JSON payload, when the kind carries one.
   */
  const char *payload;
} PcEvent;

/**
 * Shell-provided event sink. Invoked on the core's single dispatch thread;
 * implementations must hop to their UI thread themselves.
 */
typedef void (*PcEventCallback)(const struct PcEvent *event, void *userdata);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the core version as a static nul-terminated UTF-8 string.
 * The returned pointer is owned by the core; do not free it.
 */
const char *pc_version(void);

/**
 * Creates a core instance whose events are delivered to `callback` with
 * `userdata`, one at a time, on a single core-owned thread.
 */
struct PcApp *pc_app_new(PcEventCallback callback, void *userdata);

/**
 * Releases an app handle. Joins the dispatch thread: after this returns,
 * the callback is guaranteed not to run again.
 */
void pc_app_free(struct PcApp *app);

/**
 * Asks the core to answer with a `PC_EVENT_PONG` carrying `seq`, from a
 * worker thread — the smallest possible proof of the async round trip.
 */
void pc_app_ping(struct PcApp *app, uint64_t seq);

/**
 * Opens a review session over a literal unified-diff text.
 *
 * Returns null on failure; when `error_out` is non-null it receives a
 * human-readable message to release with [`pc_string_free`].
 */
struct PcSession *pc_session_new_from_patch(const char *title,
                                            uintptr_t title_len,
                                            const char *patch,
                                            uintptr_t patch_len,
                                            char **error_out);

/**
 * Opens a session over a file on disk: a unified diff, or a
 * review-exchange document (detected by content, never filename — an
 * exchange session rewrites its file on every save).
 */
struct PcSession *pc_session_new_from_file(const char *path, uintptr_t path_len, char **error_out);

/**
 * Opens a session over a local git comparison rooted at `repo`.
 */
struct PcSession *pc_session_new_from_git(const char *repo,
                                          uintptr_t repo_len,
                                          uint32_t kind,
                                          const char *arg1,
                                          uintptr_t arg1_len,
                                          const char *arg2,
                                          uintptr_t arg2_len,
                                          uint32_t context,
                                          char **error_out);

/**
 * Opens a session over a pull request. `reference` accepts every spelling
 * (URL, `owner/repo#N`, bare number); `repo_hint` is a local checkout used
 * to infer host/owner/repo for underspecified references (may be empty).
 * `config_path` locates config.json for forge-kind overrides and the
 * Forgejo transport template (may be empty).
 *
 * Fetches the host's canonical diff, metadata, and review threads through
 * the forge CLI — a blocking call; run it off the UI thread and hand the
 * session over once built.
 */
struct PcSession *pc_session_new_from_pr(const char *reference,
                                         uintptr_t reference_len,
                                         const char *repo_hint,
                                         uintptr_t repo_hint_len,
                                         const char *config_path,
                                         uintptr_t config_path_len,
                                         char **error_out);

/**
 * Releases a session handle.
 */
void pc_session_free(struct PcSession *session);

/**
 * The session title. Release with [`pc_string_free`].
 */
char *pc_session_title(const struct PcSession *session);

/**
 * Number of changed files in the session.
 */
uintptr_t pc_session_file_count(const struct PcSession *session);

/**
 * One changed file, hunks and lines included, as JSON:
 * `{old_path, new_path, status, is_binary, hunks: [{header, lines: [{kind,
 * text, raw?, old_line?, new_line?, patch_position?}]}]}`.
 * Returns null for an out-of-range index. Release with [`pc_string_free`].
 */
char *pc_session_file_json(const struct PcSession *session, uintptr_t index);

/**
 * Attaches the persistence directory: loads any saved draft for this
 * source (re-anchoring it if the head moved) and persists every later
 * change. Returns a warning string when the saved draft was unreadable
 * (released with [`pc_string_free`]), null otherwise.
 */
char *pc_session_attach_store(struct PcSession *session, const char *dir, uintptr_t dir_len);

/**
 * Sets the author attributed to new comments and replies.
 */
void pc_session_set_author(struct PcSession *session, const char *author, uintptr_t author_len);

/**
 * Adds a draft comment on one side of one file's lines. `reply_to` is a
 * host comment id (0 = a plain comment). Validates host semantics,
 * captures anchor and snippet, persists, and returns the new comment's
 * local id — or null with `error_out` set.
 */
char *pc_session_add_comment(struct PcSession *session,
                             uintptr_t file_index,
                             uint32_t side,
                             uint32_t start_line,
                             uint32_t end_line,
                             const char *body,
                             uintptr_t body_len,
                             int64_t reply_to,
                             char **error_out);

/**
 * Rewrites a draft comment's body. `false` if the id is unknown.
 */
bool pc_session_update_comment(struct PcSession *session,
                               const char *local_id,
                               uintptr_t local_id_len,
                               const char *body,
                               uintptr_t body_len);

/**
 * Deletes a draft comment. `false` if the id is unknown.
 */
bool pc_session_delete_comment(struct PcSession *session,
                               const char *local_id,
                               uintptr_t local_id_len);

/**
 * Dismiss ↔ restore a draft comment (kept, never submitted while
 * dismissed).
 */
bool pc_session_toggle_dismiss(struct PcSession *session,
                               const char *local_id,
                               uintptr_t local_id_len);

/**
 * Appends a reply to a draft comment's travelling conversation.
 */
bool pc_session_add_reply(struct PcSession *session,
                          const char *local_id,
                          uintptr_t local_id_len,
                          const char *body,
                          uintptr_t body_len);

/**
 * Every draft comment (with its location and state) as a JSON array.
 * Release with [`pc_string_free`].
 */
char *pc_session_comments_json(const struct PcSession *session);

/**
 * Existing host review threads as a JSON array (empty string outside PR
 * mode). Release with [`pc_string_free`].
 */
char *pc_session_threads_json(const struct PcSession *session);

/**
 * Pull-request metadata as JSON (empty string outside PR mode). Release
 * with [`pc_string_free`].
 */
char *pc_session_pr_json(const struct PcSession *session);

/**
 * The review summary.
 */
char *pc_session_summary(const struct PcSession *session);

/**
 * Sets the review summary (persisted immediately).
 */
bool pc_session_set_summary(struct PcSession *session, const char *summary, uintptr_t summary_len);

/**
 * Sets the submission event.
 */
void pc_session_set_event(struct PcSession *session, uint32_t event);

/**
 * Exports the review to `path`: `.json` writes a review-exchange
 * document, anything else Markdown. `false` with `error_out` on failure.
 */
bool pc_session_export_to_file(const struct PcSession *session,
                               const char *path,
                               uintptr_t path_len,
                               char **error_out);

/**
 * Submits the draft to the pull request: one atomic review, then staged
 * replies, then conversation comments. Blocking — run off the UI thread.
 *
 * Returns JSON `{"posted": n, "remaining": n, "skipped_dismissed": n,
 * "skipped_orphaned": n, "error": "…"|null}`. Accepted drafts are removed
 * and the draft persisted **before** any error is reported, so a retry
 * sends only what is still pending — never a duplicate. Null only for a
 * session that is not in PR mode.
 */
char *pc_session_submit(struct PcSession *session);

/**
 * Loads the configuration file at `path`. Never fails: a missing file is
 * the defaults, a broken one is defaults plus a load warning (the file is
 * left untouched). Returns null only for invalid UTF-8 in `path`.
 */
struct PcConfig *pc_config_new(const char *path, uintptr_t path_len);

/**
 * Releases a configuration handle.
 */
void pc_config_free(struct PcConfig *config);

/**
 * The problem found while loading, or null when the file loaded cleanly
 * (or did not exist). Release with [`pc_string_free`].
 */
char *pc_config_load_warning(const struct PcConfig *config);

/**
 * Key-binding overrides as a JSON object string (`{"action": "key spec"}`;
 * an empty spec unbinds the default). Release with [`pc_string_free`].
 */
char *pc_config_keys_json(const struct PcConfig *config);

/**
 * The syntax style table as a JSON array of `{light, dark, flags}`
 * (colors 0xRRGGBBAA as numbers; flags bit 0 = bold, bit 1 = italic).
 * Style ids in highlight spans index this table. Release with
 * [`pc_string_free`].
 */
char *pc_style_table_json(void);

/**
 * Syntax highlights for one file: JSON `[hunk][line][ [start, end,
 * style], … ]` with byte offsets into each line's display text. Null when
 * the file's language is unknown. Release with [`pc_string_free`].
 */
char *pc_session_file_highlights_json(const struct PcSession *session, uintptr_t index);

/**
 * Releases a string returned by this API.
 */
void pc_string_free(char *text);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
