/* prchum.h — C interface to the Prchum core. Generated by cbindgen; do not edit. */

#pragma once

/* Generated with cbindgen:0.29.4 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Event kind: reply to `pc_app_ping`.
 */
#define PC_EVENT_PONG 1

/**
 * Git comparison kinds for [`pc_session_new_from_git`].
 */
#define PC_GIT_WORKTREE 0

/**
 * Index vs HEAD.
 */
#define PC_GIT_STAGED 1

/**
 * `arg1...HEAD` (merge base).
 */
#define PC_GIT_BASE 2

/**
 * Explicit range `arg1..arg2`.
 */
#define PC_GIT_RANGE 3

/**
 * Side values crossing the boundary.
 */
#define PC_SIDE_LEFT 0

#define PC_SIDE_RIGHT 1

/**
 * Review events crossing the boundary.
 */
#define PC_EVENT_REVIEW_COMMENT 0

#define PC_EVENT_REVIEW_APPROVE 1

#define PC_EVENT_REVIEW_REQUEST_CHANGES 2

/**
 * Root handle for a core instance. Create with [`pc_app_new`], release with
 * [`pc_app_free`].
 */
typedef struct PcApp PcApp;

/**
 * The user configuration. Create with [`pc_config_new`], release with
 * [`pc_config_free`].
 */
typedef struct PcConfig PcConfig;

/**
 * A review session over one diff source. Create with one of the
 * `pc_session_new_*` constructors, release with [`pc_session_free`].
 *
 * The session is internally synchronized: calls may arrive from more
 * than one thread (the shell runs slow operations — submission, the
 * first context fetch — off its UI thread) and serialize on a mutex.
 */
typedef struct PcSession PcSession;

/**
 * An event delivered from the core to the shell.
 *
 * The struct and every string it points to are only valid for the duration
 * of the callback invocation; copy anything you need out of it. Strings not
 * applicable to the event kind are null. Shells must tolerate unknown
 * kinds — new kinds are forward compatibility, not an error.
 */
typedef struct PcEvent {
  /**
   * One of the `PC_EVENT_*` constants.
   */
  uint32_t kind;
  /**
   * Sequence number (pong events).
   */
  uint64_t seq;
  /**
   * JSON payload, when the kind carries one.
   */
  const char *payload;
} PcEvent;

/**
 * Shell-provided event sink. Invoked on the core's single dispatch thread;
 * implementations must hop to their UI thread themselves.
 */
typedef void (*PcEventCallback)(const struct PcEvent *event, void *userdata);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the core version as a static nul-terminated UTF-8 string.
 * The returned pointer is owned by the core; do not free it.
 */
const char *pc_version(void);

/**
 * Creates a core instance whose events are delivered to `callback` with
 * `userdata`, one at a time, on a single core-owned thread.
 */
struct PcApp *pc_app_new(PcEventCallback callback, void *userdata);

/**
 * Releases an app handle. Joins the dispatch thread: after this returns,
 * the callback is guaranteed not to run again.
 */
void pc_app_free(struct PcApp *app);

/**
 * Asks the core to answer with a `PC_EVENT_PONG` carrying `seq`, from a
 * worker thread — the smallest possible proof of the async round trip.
 */
void pc_app_ping(struct PcApp *app, uint64_t seq);

/**
 * Opens a review session over a literal unified-diff text.
 *
 * Returns null on failure; when `error_out` is non-null it receives a
 * human-readable message to release with [`pc_string_free`].
 */
struct PcSession *pc_session_new_from_patch(const char *title,
                                            uintptr_t title_len,
                                            const char *patch,
                                            uintptr_t patch_len,
                                            char **error_out);

/**
 * Opens a session over a file on disk: a unified diff, or a
 * review-exchange document (detected by content, never filename — an
 * exchange session rewrites its file on every save).
 */
struct PcSession *pc_session_new_from_file(const char *path, uintptr_t path_len, char **error_out);

/**
 * Opens a session over a local git comparison rooted at `repo`.
 */
struct PcSession *pc_session_new_from_git(const char *repo,
                                          uintptr_t repo_len,
                                          uint32_t kind,
                                          const char *arg1,
                                          uintptr_t arg1_len,
                                          const char *arg2,
                                          uintptr_t arg2_len,
                                          uint32_t context,
                                          char **error_out);

/**
 * Opens a session over a pull request. `reference` accepts every spelling
 * (URL, `owner/repo#N`, bare number); `repo_hint` is a local checkout used
 * to infer host/owner/repo for underspecified references (may be empty).
 * `config_path` locates config.json for forge-kind overrides and the
 * Forgejo transport template (may be empty).
 *
 * Fetches the host's canonical diff, metadata, and review threads through
 * the forge CLI — a blocking call; run it off the UI thread and hand the
 * session over once built.
 */
struct PcSession *pc_session_new_from_pr(const char *reference,
                                         uintptr_t reference_len,
                                         const char *repo_hint,
                                         uintptr_t repo_hint_len,
                                         const char *config_path,
                                         uintptr_t config_path_len,
                                         char **error_out);

/**
 * The whole-file projection of one file — the context view: content
 * fetched through the source (blocking for PR sessions; run off the UI
 * thread on first use), verified against the diff, hunks overlaid. Same
 * JSON shape as [`pc_session_file_json`]. Null with `error_out` set when
 * the source has no content (plain patches), the file is deleted, or the
 * content does not match the diff.
 */
char *pc_session_context_file_json(struct PcSession *session, uintptr_t index, char **error_out);

/**
 * Releases a session handle.
 */
void pc_session_free(struct PcSession *session);

/**
 * The session title. Release with [`pc_string_free`].
 */
char *pc_session_title(const struct PcSession *session);

/**
 * Number of changed files in the session.
 */
uintptr_t pc_session_file_count(const struct PcSession *session);

/**
 * One changed file, hunks and lines included, as JSON:
 * `{old_path, new_path, status, is_binary, hunks: [{header, lines: [{kind,
 * text, raw?, old_line?, new_line?, patch_position?}]}]}`.
 * Returns null for an out-of-range index. Release with [`pc_string_free`].
 */
char *pc_session_file_json(const struct PcSession *session, uintptr_t index);

/**
 * Attaches the persistence directory: loads any saved draft for this
 * source (re-anchoring it if the head moved) and persists every later
 * change. Returns a warning string when the saved draft was unreadable
 * (released with [`pc_string_free`]), null otherwise.
 */
char *pc_session_attach_store(struct PcSession *session, const char *dir, uintptr_t dir_len);

/**
 * Sets the author attributed to new comments and replies.
 */
void pc_session_set_author(struct PcSession *session, const char *author, uintptr_t author_len);

/**
 * Adds a draft comment on one side of one file's lines. `reply_to` is a
 * host comment id (0 = a plain comment). Validates host semantics,
 * captures anchor and snippet, persists, and returns the new comment's
 * local id — or null with `error_out` set.
 */
char *pc_session_add_comment(struct PcSession *session,
                             uintptr_t file_index,
                             uint32_t side,
                             uint32_t start_line,
                             uint32_t end_line,
                             const char *body,
                             uintptr_t body_len,
                             int64_t reply_to,
                             char **error_out);

/**
 * Rewrites a draft comment's body. `false` if the id is unknown.
 */
bool pc_session_update_comment(struct PcSession *session,
                               const char *local_id,
                               uintptr_t local_id_len,
                               const char *body,
                               uintptr_t body_len);

/**
 * Deletes a draft comment. `false` if the id is unknown.
 */
bool pc_session_delete_comment(struct PcSession *session,
                               const char *local_id,
                               uintptr_t local_id_len);

/**
 * Dismiss ↔ restore a draft comment (kept, never submitted while
 * dismissed).
 */
bool pc_session_toggle_dismiss(struct PcSession *session,
                               const char *local_id,
                               uintptr_t local_id_len);

/**
 * Appends a reply to a draft comment's travelling conversation.
 */
bool pc_session_add_reply(struct PcSession *session,
                          const char *local_id,
                          uintptr_t local_id_len,
                          const char *body,
                          uintptr_t body_len);

/**
 * Rewrites one reply of a draft's conversation (authors stay).
 */
bool pc_session_update_reply(struct PcSession *session,
                             const char *local_id,
                             uintptr_t local_id_len,
                             uintptr_t index,
                             const char *body,
                             uintptr_t body_len);

/**
 * Deletes one reply of a draft's conversation.
 */
bool pc_session_delete_reply(struct PcSession *session,
                             const char *local_id,
                             uintptr_t local_id_len,
                             uintptr_t index);

/**
 * Every draft comment (with its location and state) as a JSON array.
 * Release with [`pc_string_free`].
 */
char *pc_session_comments_json(const struct PcSession *session);

/**
 * Existing host review threads as a JSON array (empty string outside PR
 * mode). Release with [`pc_string_free`].
 */
char *pc_session_threads_json(const struct PcSession *session);

/**
 * Pull-request metadata as JSON (empty string outside PR mode). Release
 * with [`pc_string_free`].
 */
char *pc_session_pr_json(const struct PcSession *session);

/**
 * The review summary.
 */
char *pc_session_summary(const struct PcSession *session);

/**
 * Sets the review summary (persisted immediately).
 */
bool pc_session_set_summary(struct PcSession *session, const char *summary, uintptr_t summary_len);

/**
 * Sets the submission event.
 */
void pc_session_set_event(struct PcSession *session, uint32_t event);

/**
 * Exports the review to `path`: `.json` writes a review-exchange
 * document, anything else Markdown. `false` with `error_out` on failure.
 */
bool pc_session_export_to_file(const struct PcSession *session,
                               const char *path,
                               uintptr_t path_len,
                               char **error_out);

/**
 * Submits the draft to the pull request: one atomic review, then staged
 * replies, then conversation comments. Blocking — run off the UI thread.
 *
 * Returns JSON `{"posted": n, "remaining": n, "skipped_dismissed": n,
 * "skipped_orphaned": n, "error": "…"|null}`. Accepted drafts are removed
 * and the draft persisted **before** any error is reported, so a retry
 * sends only what is still pending — never a duplicate. Null only for a
 * session that is not in PR mode.
 */
char *pc_session_submit(struct PcSession *session);

/**
 * Loads the configuration file at `path`. Never fails: a missing file is
 * the defaults, a broken one is defaults plus a load warning (the file is
 * left untouched). Returns null only for invalid UTF-8 in `path`.
 */
struct PcConfig *pc_config_new(const char *path, uintptr_t path_len);

/**
 * Releases a configuration handle.
 */
void pc_config_free(struct PcConfig *config);

/**
 * The problem found while loading, or null when the file loaded cleanly
 * (or did not exist). Release with [`pc_string_free`].
 */
char *pc_config_load_warning(const struct PcConfig *config);

/**
 * The selected named keymap, or an empty string. `exists_out` (when
 * non-null) reports whether `keymaps` defines it — the shell warns on a
 * typo. Release with [`pc_string_free`].
 */
char *pc_config_keymap(const struct PcConfig *config, bool *exists_out);

/**
 * The named discovery filters as a JSON object (`{name: filter}`).
 * Release with [`pc_string_free`].
 */
char *pc_config_list_filters_json(const struct PcConfig *config);

/**
 * The fallback discovery filter (empty = the engine's default).
 * Release with [`pc_string_free`].
 */
char *pc_config_list_filter(const struct PcConfig *config);

/**
 * Writes one entry of a top-level map setting (`list_filters`, `keys`,
 * `forges`…) into config.json, preserving everything else. An empty
 * value removes the entry; a broken file is left untouched.
 */
bool pc_config_set_map_entry(const char *config_path,
                             uintptr_t config_path_len,
                             const char *map_key,
                             uintptr_t map_key_len,
                             const char *entry_key,
                             uintptr_t entry_key_len,
                             const char *value,
                             uintptr_t value_len);

/**
 * The configured appearance: 0 = system, 1 = light, 2 = dark.
 */
uint32_t pc_config_appearance(const struct PcConfig *config);

/**
 * The configured theme name (empty = default). Release with
 * [`pc_string_free`].
 */
char *pc_config_theme(const struct PcConfig *config);

/**
 * Key-binding overrides as a JSON object string (`{"action": "key spec"}`;
 * an empty spec unbinds the default). Release with [`pc_string_free`].
 */
char *pc_config_keys_json(const struct PcConfig *config);

/**
 * Lists the open requests waiting for the user's review, through the
 * engine the config selects (`list_engine`: `gh` default, or `forgejo`
 * with `list_host`). `filter` overrides the config's `list_filter`
 * (empty = use it). Blocking — run off the UI thread. Returns a JSON
 * array of `{host, owner, repo, number, title, author, updated_at, url}`
 * or null with `error_out` set. Release with [`pc_string_free`].
 */
char *pc_list_requests(const char *config_path,
                       uintptr_t config_path_len,
                       const char *filter,
                       uintptr_t filter_len,
                       char **error_out);

/**
 * Host conversation-level comments (PR mode) as a JSON array (empty
 * string otherwise). Release with [`pc_string_free`].
 */
char *pc_session_general_json(const struct PcSession *session);

/**
 * The staged conversation comments as a JSON array. Release with
 * [`pc_string_free`].
 */
char *pc_session_general_drafts_json(const struct PcSession *session);

/**
 * Stages a conversation-level comment (posts on submit). Returns its
 * local id, or null. Release with [`pc_string_free`].
 */
char *pc_session_add_general(struct PcSession *session, const char *body, uintptr_t body_len);

/**
 * Deletes a staged conversation comment by local id.
 */
bool pc_session_delete_general(struct PcSession *session,
                               const char *local_id,
                               uintptr_t local_id_len);

/**
 * Records (or refreshes) this session in the review history at `dir`.
 * `submitted` also stamps the submission time. `false` on failure.
 */
bool pc_session_record_history(const struct PcSession *session,
                               const char *dir,
                               uintptr_t dir_len,
                               bool submitted);

/**
 * The review history at `dir` as a JSON array, newest first. Release
 * with [`pc_string_free`].
 */
char *pc_history_list_json(const char *dir, uintptr_t dir_len);

/**
 * Removes one history entry by source key (the user's hand deletion).
 */
bool pc_history_remove(const char *dir, uintptr_t dir_len, const char *key, uintptr_t key_len);

/**
 * Prunes history entries whose pull request is merged, closed, or gone,
 * asking each entry's forge. Blocking (one network call per PR entry) —
 * run off the UI thread. Network failures never prune; only a definite
 * answer does. Returns the surviving entries as JSON, newest first.
 */
char *pc_history_prune_json(const char *dir,
                            uintptr_t dir_len,
                            const char *config_path,
                            uintptr_t config_path_len);

/**
 * Built-in theme names, newline-joined, in presentation order.
 * Release with [`pc_string_free`].
 */
char *pc_theme_builtin_names(void);

/**
 * Syntax highlights for the context projection of one file: same JSON
 * shape as [`pc_session_file_highlights_json`], but indexed by the
 * projection's hunks, so gap regions color too. Null when the language
 * is unknown or the projection is unavailable. Cached content — cheap
 * after the first [`pc_session_context_file_json`]. Release with
 * [`pc_string_free`].
 */
char *pc_session_context_highlights_json(struct PcSession *session, uintptr_t index);

/**
 * The syntax style table as a JSON array of `{light, dark, flags}`
 * (colors 0xRRGGBBAA as numbers; flags bit 0 = bold, bit 1 = italic).
 * Style ids in highlight spans index this table. Release with
 * [`pc_string_free`].
 */
char *pc_style_table_json(void);

/**
 * Applies the theme config.json names: a built-in (`default`,
 * `high-contrast`) or a `themes/<name>.json` next to the config file.
 * Returns a warning string when the theme could not apply (the default
 * stays), null on success. Release with [`pc_string_free`].
 */
char *pc_theme_apply(const char *config_path, uintptr_t config_path_len);

/**
 * Writes one string setting into config.json, preserving everything
 * else in the file (unknown keys included). `false` with the file left
 * untouched on any problem.
 */
bool pc_config_set_string(const char *config_path,
                          uintptr_t config_path_len,
                          const char *key,
                          uintptr_t key_len,
                          const char *value,
                          uintptr_t value_len);

/**
 * Syntax highlights for one file: JSON `[hunk][line][ [start, end,
 * style], … ]` with byte offsets into each line's display text. Null when
 * the file's language is unknown. Release with [`pc_string_free`].
 */
char *pc_session_file_highlights_json(const struct PcSession *session, uintptr_t index);

/**
 * Releases a string returned by this API.
 */
void pc_string_free(char *text);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
